# Generated by Django 4.2.27 on 2026-01-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome da conta')),
                ('institution', models.CharField(blank=True, max_length=100, verbose_name='Instituição financeira')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='Número da conta')),
                ('account_type', models.CharField(choices=[('CASH', 'Dinheiro'), ('BANK', 'Banco'), ('INVEST', 'Investimento')], default='BANK', max_length=10, verbose_name='Tipo')),
                ('currency', models.CharField(default='Real brasileiro', max_length=30, verbose_name='Unidade monetária')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo de abertura')),
                ('minimum_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo mínimo')),
                ('group', models.CharField(blank=True, max_length=100, verbose_name='Grupo de contas')),
                ('abbreviation', models.CharField(blank=True, max_length=20, verbose_name='Abreviação')),
                ('comment', models.TextField(blank=True, verbose_name='Comentário')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Conta favorita')),
                ('is_closed', models.BooleanField(default=False, verbose_name='A conta está encerrada')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
            },
        ),
    ]
