# Generated by Django 4.2.27 on 2026-01-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('full_name', models.CharField(max_length=200, verbose_name='Nome completo')),
            ],
            options={
                'verbose_name': 'Beneficiário',
                'verbose_name_plural': 'Beneficiários',
            },
        ),
    ]
