# Generated by Django 4.2.27 on 2026-01-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_beneficiary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.CharField(max_length=200, verbose_name='Categoria')),
                ('subcategory', models.CharField(max_length=200, verbose_name='Subcategoria')),
                ('default_transaction_type', models.CharField(choices=[('CR', 'Credit'), ('DB', 'Debit')], default='DB', max_length=2, verbose_name='Tipo de transação padrão')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ('category', 'subcategory'),
            },
        ),
    ]
