# Generated by Django 4.2.27 on 2026-01-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='abbreviation',
        ),
        migrations.RemoveField(
            model_name='account',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='account',
            name='group',
        ),
        migrations.RemoveField(
            model_name='account',
            name='minimum_balance',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('CASH', 'Dinheiro'), ('BANK', 'Banco'), ('INVEST', 'Investimento'), ('CREDCARD', 'Cartão de crédito')], default='BANK', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='default_transaction_type',
            field=models.CharField(choices=[('CR', 'Crédito'), ('DB', 'Débito')], default='DB', max_length=2, verbose_name='Tipo de transação padrão'),
        ),
    ]
