# Generated by Django 4.2.27 on 2026-01-06 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_remove_account_abbreviation_remove_account_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='account',
            name='number',
        ),
    ]
