# Generated by Django 4.2.23 on 2026-01-06 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_account_institution_remove_account_is_closed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Data do vencimento')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Data do registro')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Data da compra')),
                ('notes', models.TextField(blank=True, verbose_name='Anotações')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.account', verbose_name='Conta')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.beneficiary', verbose_name='Beneficiário')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ('-created_at',),
            },
        ),
    ]
