# Generated by Django 4.2.23 on 2026-01-06 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Data do vencimento')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Data da compra')),
                ('notes', models.TextField(blank=True, verbose_name='Anotações')),
                ('recurrence_type', models.CharField(choices=[('DAILY', 'Diária'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensal'), ('YEARLY', 'Anual')], default='MONTHLY', max_length=10, verbose_name='Tipo de recorrência')),
                ('recurrence_interval', models.IntegerField(default=1, verbose_name='Intervalo da recorrência')),
                ('termination_type', models.CharField(choices=[('INFINITE', 'Infinito'), ('INSTALLMENTS', 'Número de parcelas'), ('FINAL_DATE', 'Data final')], default='INFINITE', max_length=15, verbose_name='Tipo de término')),
                ('remaining_installments', models.IntegerField(blank=True, null=True, verbose_name='Parcelas restantes')),
                ('final_date', models.DateField(blank=True, null=True, verbose_name='Data final')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('PAUSED', 'Pausado'), ('COMPLETED', 'Concluído')], default='ACTIVE', max_length=10, verbose_name='Status')),
                ('original_due_date', models.DateField(blank=True, null=True, verbose_name='Data de vencimento original')),
                ('registered_count', models.IntegerField(default=0, verbose_name='Contador de registros')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.account', verbose_name='Conta')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.beneficiary', verbose_name='Beneficiário')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ('-created_at',),
            },
        ),
    ]
