# Generated by Django 4.2.23 on 2026-01-07 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_split_category_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_transfer',
            field=models.BooleanField(default=False, help_text='Indica se esta transação faz parte de uma transferência entre contas', verbose_name='É transferência'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_group_id',
            field=models.UUIDField(blank=True, help_text='UUID que vincula as duas transações de uma transferência', null=True, verbose_name='ID do grupo de transferência'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.beneficiary', verbose_name='Beneficiário'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.subcategory', verbose_name='Subcategoria'),
        ),
    ]
