# Generated by Django 4.2.23 on 2026-01-07 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_transaction_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Data do vencimento')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Data da compra')),
                ('notes', models.TextField(blank=True, verbose_name='Anotações')),
                ('recurrence_type', models.CharField(choices=[('DAILY', 'Diária'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensal'), ('YEARLY', 'Anual')], default='MONTHLY', max_length=10, verbose_name='Tipo de recorrência')),
                ('recurrence_interval', models.IntegerField(default=1, verbose_name='Intervalo da recorrência')),
                ('termination_type', models.CharField(choices=[('INFINITE', 'Infinito'), ('INSTALLMENTS', 'Número de parcelas'), ('FINAL_DATE', 'Data final')], default='INFINITE', max_length=15, verbose_name='Tipo de término')),
                ('remaining_installments', models.IntegerField(blank=True, null=True, verbose_name='Parcelas restantes')),
                ('final_date', models.DateField(blank=True, null=True, verbose_name='Data final')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('PAUSED', 'Pausado'), ('COMPLETED', 'Concluído')], default='ACTIVE', max_length=10, verbose_name='Status')),
                ('original_due_date', models.DateField(blank=True, null=True, verbose_name='Data de vencimento original')),
                ('registered_count', models.IntegerField(default=0, verbose_name='Contador de registros')),
            ],
            options={
                'verbose_name': 'Agendamento Múltiplo',
                'verbose_name_plural': 'Agendamentos Múltiplos',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_multiple',
            field=models.BooleanField(default=False, help_text='Indica se esta transação faz parte de uma transação múltipla', verbose_name='É transação múltipla'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='multiple_transaction_group_id',
            field=models.UUIDField(blank=True, help_text='UUID que vincula as transações de uma transação múltipla', null=True, verbose_name='ID do grupo de transação múltipla'),
        ),
        migrations.CreateModel(
            name='MultipleSchedulerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('transaction_type', models.CharField(choices=[('CR', 'Crédito'), ('DB', 'Débito')], default='DB', max_length=2, verbose_name='Tipo de transação')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('item_order', models.IntegerField(default=0, help_text='Ordem de exibição do item', verbose_name='Ordem')),
                ('is_transfer', models.BooleanField(default=False, help_text='Indica se este item é uma transferência entre contas', verbose_name='É transferência')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.account', verbose_name='Conta')),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.beneficiary', verbose_name='Beneficiário')),
                ('destination_account', models.ForeignKey(blank=True, help_text='Conta de destino (apenas para transferências)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multiple_scheduler_destination_items', to='finance.account', verbose_name='Conta de destino')),
                ('scheduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.multiplescheduler', verbose_name='Agendamento Múltiplo')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.subcategory', verbose_name='Subcategoria')),
            ],
            options={
                'verbose_name': 'Item de Agendamento Múltiplo',
                'verbose_name_plural': 'Itens de Agendamento Múltiplo',
                'ordering': ('item_order', 'id'),
            },
        ),
    ]
