# Generated by Django 4.2.23 on 2026-01-07 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_multiplescheduler_transaction_is_multiple_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplescheduleritem',
            name='account',
        ),
        migrations.RemoveField(
            model_name='multiplescheduleritem',
            name='beneficiary',
        ),
        migrations.AddField(
            model_name='multiplescheduler',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.account', verbose_name='Conta'),
        ),
        migrations.AddField(
            model_name='multiplescheduler',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.beneficiary', verbose_name='Beneficiário'),
        ),
        migrations.AddField(
            model_name='multiplescheduleritem',
            name='source_account',
            field=models.ForeignKey(blank=True, help_text='Conta de origem (apenas para transferências)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multiple_scheduler_source_items', to='finance.account', verbose_name='Conta de origem'),
        ),
    ]
