# Generated by Django 4.2.23 on 2026-01-07 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_remove_multiplescheduleritem_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplescheduleritem',
            name='source_account',
        ),
    ]
