# Generated by Django 4.2.23 on 2026-01-07 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_remove_source_account_from_multiple_scheduler_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='multiple_scheduler_group_id',
            field=models.UUIDField(blank=True, help_text='UUID que vincula os agendamentos de um agendamento múltiplo', null=True, verbose_name='ID do grupo de agendamento múltiplo'),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='is_multiple',
            field=models.BooleanField(default=False, help_text='Indica se este agendamento faz parte de um agendamento múltiplo', verbose_name='É agendamento múltiplo'),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='is_transfer',
            field=models.BooleanField(default=False, help_text='Indica se este agendamento é uma transferência entre contas (apenas para múltiplos)', verbose_name='É transferência'),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='destination_account',
            field=models.ForeignKey(blank=True, help_text='Conta de destino (apenas para transferências em agendamentos múltiplos)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduler_destination_items', to='finance.account', verbose_name='Conta de destino'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.subcategory', verbose_name='Subcategoria'),
        ),
    ]
