# Generated by Django 4.2.23 on 2026-01-07 13:15

from django.db import migrations
import uuid


def migrate_multiple_scheduler_data(apps, schema_editor):
    """Migra dados de MultipleScheduler e MultipleSchedulerItem para Scheduler"""
    MultipleScheduler = apps.get_model('finance', 'MultipleScheduler')
    MultipleSchedulerItem = apps.get_model('finance', 'MultipleSchedulerItem')
    Scheduler = apps.get_model('finance', 'Scheduler')
    
    # Para cada MultipleScheduler, criar Schedulers para cada item
    for multiple_scheduler in MultipleScheduler.objects.all():
        group_id = uuid.uuid4()
        items = MultipleSchedulerItem.objects.filter(scheduler=multiple_scheduler).order_by('item_order', 'id')
        
        for item in items:
            # Criar um Scheduler para cada item
            scheduler = Scheduler(
                account=multiple_scheduler.account,
                beneficiary=multiple_scheduler.beneficiary,
                subcategory=item.subcategory,
                transaction_type=item.transaction_type,
                value=item.value,
                due_date=multiple_scheduler.due_date,
                purchase_date=multiple_scheduler.purchase_date,
                notes=multiple_scheduler.notes,
                recurrence_type=multiple_scheduler.recurrence_type,
                recurrence_interval=multiple_scheduler.recurrence_interval,
                termination_type=multiple_scheduler.termination_type,
                remaining_installments=multiple_scheduler.remaining_installments,
                final_date=multiple_scheduler.final_date,
                status=multiple_scheduler.status,
                original_due_date=multiple_scheduler.original_due_date,
                registered_count=multiple_scheduler.registered_count,
                multiple_scheduler_group_id=group_id,
                is_multiple=True,
                is_transfer=item.is_transfer,
                destination_account=item.destination_account,
                created_at=multiple_scheduler.created_at,
                updated_at=multiple_scheduler.updated_at,
            )
            scheduler.save()


def reverse_migration(apps, schema_editor):
    """Reverter migração - remover Schedulers múltiplos"""
    Scheduler = apps.get_model('finance', 'Scheduler')
    Scheduler.objects.filter(is_multiple=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_add_multiple_fields_to_scheduler'),
    ]

    operations = [
        migrations.RunPython(migrate_multiple_scheduler_data, reverse_migration),
    ]
