# Generated by Django 4.2.23 on 2026-01-07 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_migrate_multiple_scheduler_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleSchedulerItem',
        ),
        migrations.DeleteModel(
            name='MultipleScheduler',
        ),
    ]

