# Generated by Django 4.2.27 on 2026-01-08 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_remove_multiple_scheduler_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(help_text='Código do ativo (ex: PETR4, HGLG11, CDB123)', max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(help_text='Nome completo do ativo', max_length=200, verbose_name='Nome')),
                ('asset_type', models.CharField(choices=[('STOCK', 'Ação'), ('FII', 'Fundo Imobiliário'), ('ETF', 'ETF'), ('BOND', 'Renda Fixa'), ('REIT', 'REIT'), ('CRYPTO', 'Criptomoeda'), ('OTHER', 'Outro')], default='STOCK', max_length=10, verbose_name='Tipo de ativo')),
                ('sector', models.CharField(blank=True, help_text='Setor do ativo (ex: Petróleo, Varejo)', max_length=100, verbose_name='Setor')),
                ('currency', models.CharField(default='BRL', help_text='Moeda de negociação (BRL, USD, etc.)', max_length=10, verbose_name='Moeda')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='AssetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('operation_type', models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venda'), ('DIVIDEND', 'Dividendo'), ('JCP', 'Juros sobre Capital Próprio'), ('BONUS', 'Bonificação'), ('SPLIT', 'Desdobramento'), ('GROUP', 'Grupamento'), ('SUB', 'Subscrição'), ('CAPITAL_INCREASE', 'Aumento de Capital'), ('RIGHTS_EXERCISE', 'Exercício de Direitos'), ('AMORTIZATION', 'Amortização'), ('INTEREST', 'Juros (Renda Fixa)'), ('REDEMPTION', 'Resgate (Renda Fixa)')], max_length=20, verbose_name='Tipo de operação')),
                ('date', models.DateField(verbose_name='Data da operação')),
                ('quantity', models.DecimalField(decimal_places=6, default=0, help_text='Quantidade de ativos (0 para dividendos, juros, etc.)', max_digits=15, verbose_name='Quantidade')),
                ('price', models.DecimalField(decimal_places=4, default=0, help_text='Preço por unidade (0 para dividendos, juros, etc.)', max_digits=12, verbose_name='Preço unitário')),
                ('fees', models.DecimalField(decimal_places=2, default=0, help_text='Taxas de corretagem, emolumentos, etc.', max_digits=12, verbose_name='Taxas e impostos')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, help_text='Valor total da operação (quantity * price ± fees)', max_digits=12, verbose_name='Valor total')),
                ('income_value', models.DecimalField(decimal_places=2, default=0, help_text='Valor recebido em dividendos, juros, etc.', max_digits=12, verbose_name='Valor de rendimento')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('account', models.ForeignKey(help_text='Conta onde o ativo está alocado', on_delete=django.db.models.deletion.CASCADE, to='finance.account', verbose_name='Conta')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.asset', verbose_name='Ativo')),
                ('transaction', models.ForeignKey(blank=True, help_text='Transação financeira relacionada (para integração com o sistema existente)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.transaction', verbose_name='Transação relacionada')),
            ],
            options={
                'verbose_name': 'Transação de Ativo',
                'verbose_name_plural': 'Transações de Ativos',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='AssetPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(verbose_name='Data da posição')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Quantidade')),
                ('average_cost', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Preço médio')),
                ('current_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Preço atual')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.account', verbose_name='Conta')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='finance.asset', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Posição de Ativo',
                'verbose_name_plural': 'Posições de Ativos',
                'ordering': ('-date', 'asset'),
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['code'], name='finance_ass_code_c54d66_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_type'], name='finance_ass_asset_t_eb4a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='assettransaction',
            index=models.Index(fields=['asset', 'date'], name='finance_ass_asset_i_97225b_idx'),
        ),
        migrations.AddIndex(
            model_name='assettransaction',
            index=models.Index(fields=['operation_type', 'date'], name='finance_ass_operati_13acee_idx'),
        ),
        migrations.AddIndex(
            model_name='assettransaction',
            index=models.Index(fields=['account', 'date'], name='finance_ass_account_d38ba4_idx'),
        ),
        migrations.AddIndex(
            model_name='assetposition',
            index=models.Index(fields=['asset', 'account', 'date'], name='finance_ass_asset_i_913cf8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetposition',
            unique_together={('asset', 'account', 'date')},
        ),
    ]
