# Generated by Django 4.2.23 on 2026-01-08 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_asset_assettransaction_assetposition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('budget_date', models.DateField(help_text='Data do orçamento (sempre dia 1 do mês/ano)', verbose_name='Data do orçamento')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finance.subcategory', verbose_name='Subcategoria')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ('budget_date', 'subcategory'),
                'indexes': [models.Index(fields=['subcategory', 'budget_date'], name='finance_bud_subcate_1f8954_idx'), models.Index(fields=['budget_date'], name='finance_bud_budget__d606bc_idx')],
                'unique_together': {('subcategory', 'budget_date')},
            },
        ),
    ]
