# Generated by Django 4.2.23 on 2026-01-08 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(choices=[('ELECTRO', 'Eletrodoméstico'), ('ART', 'Obra de arte'), ('BOOK', 'Livro'), ('MUSIC', 'Música'), ('OFFICE', 'Escritório'), ('TOOL', 'Ferramenta'), ('VEHICLE', 'Veículo'), ('ELECTRONIC', 'Eletrônico'), ('REAL_ESTATE', 'Imobiliário'), ('HOBBY', 'Hobby')], help_text='Categoria do bem', max_length=20, verbose_name='Tipo')),
                ('description', models.CharField(help_text='Descrição do item', max_length=200, verbose_name='Descrição')),
                ('buy_price', models.DecimalField(decimal_places=2, help_text='Valor pago na compra', max_digits=12, verbose_name='Preço de compra')),
                ('buy_date', models.DateField(help_text='Data em que o item foi adquirido', verbose_name='Data de compra')),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, help_text='Valor atual estimado do item', max_digits=12, null=True, verbose_name='Preço atual')),
                ('brand', models.CharField(blank=True, help_text='Marca do produto', max_length=100, verbose_name='Marca')),
                ('model', models.CharField(blank=True, help_text='Modelo do produto', max_length=100, verbose_name='Modelo')),
                ('serial_number', models.CharField(blank=True, help_text='Número de série do produto', max_length=100, verbose_name='Número de série')),
                ('condition', models.CharField(choices=[('NEW', 'Novo'), ('EXCELLENT', 'Excelente'), ('GOOD', 'Bom'), ('FAIR', 'Regular'), ('POOR', 'Ruim'), ('DAMAGED', 'Danificado')], default='GOOD', help_text='Estado atual do item', max_length=20, verbose_name='Condição')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('SOLD', 'Vendido'), ('DONATED', 'Doado'), ('DISCARDED', 'Descartado'), ('LOST', 'Perdido')], default='ACTIVE', help_text='Status do item no inventário', max_length=20, verbose_name='Status')),
                ('location', models.CharField(blank=True, help_text='Onde o item está guardado', max_length=200, verbose_name='Localização')),
                ('warranty_end_date', models.DateField(blank=True, help_text='Data de término da garantia', null=True, verbose_name='Data de término da garantia')),
                ('sale_date', models.DateField(blank=True, help_text='Data em que o item foi vendido', null=True, verbose_name='Data de venda')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Valor pelo qual o item foi vendido', max_digits=12, null=True, verbose_name='Preço de venda')),
                ('notes', models.TextField(blank=True, help_text='Observações adicionais sobre o item', verbose_name='Anotações')),
                ('purchase_transaction', models.ForeignKey(blank=True, help_text='Transação financeira relacionada à compra deste item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='finance.transaction', verbose_name='Transação de compra')),
            ],
            options={
                'verbose_name': 'Item do Inventário',
                'verbose_name_plural': 'Itens do Inventário',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['type', 'status'], name='finance_inv_type_7b5ab2_idx'), models.Index(fields=['status'], name='finance_inv_status_c32e18_idx'), models.Index(fields=['buy_date'], name='finance_inv_buy_dat_c30e31_idx')],
            },
        ),
    ]
