# Generated by Django 4.2.23 on 2026-01-08 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(help_text='Código do plano (ex: 1.01, 1.01.1, 2)', max_length=50, unique=True, verbose_name='Código')),
                ('description', models.CharField(help_text='Descrição do plano de contas', max_length=200, verbose_name='Descrição')),
                ('asset_type', models.CharField(blank=True, choices=[('STOCK', 'Ação'), ('FII', 'Fundo Imobiliário'), ('ETF', 'ETF'), ('BOND', 'Renda Fixa'), ('REIT', 'REIT'), ('CRYPTO', 'Criptomoeda'), ('OTHER', 'Outro')], help_text='Se preenchido, o plano totaliza transações de ativos deste tipo', max_length=10, null=True, verbose_name='Tipo de ativo')),
                ('calculation_type', models.CharField(choices=[('SUBTOTAL_CASCADE', 'Subtotal cascata'), ('TOTALIZE_TRANSACTIONS', 'Totaliza transações'), ('TOTALIZE_ASSET_TRANSACTIONS', 'Totaliza transações de ativos')], default='SUBTOTAL_CASCADE', help_text='Tipo de cálculo - detectado automaticamente', max_length=30, verbose_name='Tipo de cálculo')),
                ('accumulates_in', models.ForeignKey(blank=True, help_text='Plano onde este acumula valores (pode ser diferente do parent)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accumulated_by', to='finance.chartaccount', verbose_name='Acumula no plano')),
                ('parent', models.ForeignKey(blank=True, help_text='Plano pai na hierarquia (sugerido automaticamente baseado no código)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='finance.chartaccount', verbose_name='Plano pai')),
                ('subcategory', models.ForeignKey(blank=True, help_text='Se preenchido, o plano totaliza transações desta subcategoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.subcategory', verbose_name='Subcategoria')),
            ],
            options={
                'verbose_name': 'Plano de Contas',
                'verbose_name_plural': 'Planos de Contas',
                'ordering': ('code',),
                'indexes': [models.Index(fields=['code'], name='finance_cha_code_81a08b_idx'), models.Index(fields=['parent'], name='finance_cha_parent__2e6050_idx'), models.Index(fields=['accumulates_in'], name='finance_cha_accumul_6687f9_idx'), models.Index(fields=['subcategory'], name='finance_cha_subcate_cba346_idx'), models.Index(fields=['asset_type'], name='finance_cha_asset_t_a290ab_idx')],
            },
        ),
    ]
