# Generated by Django 4.2.23 on 2026-01-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_chartaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartaccount',
            name='asset_type',
            field=models.CharField(blank=True, choices=[('BUY', 'Compra'), ('SELL', 'Venda'), ('DIVIDEND', 'Dividendo'), ('JCP', 'Juros sobre Capital Próprio'), ('BONUS', 'Bonificação'), ('SPLIT', 'Desdobramento'), ('GROUP', 'Grupamento'), ('SUB', 'Subscrição'), ('CAPITAL_INCREASE', 'Aumento de Capital'), ('RIGHTS_EXERCISE', 'Exercício de Direitos'), ('AMORTIZATION', 'Amortização'), ('INTEREST', 'Juros (Renda Fixa)'), ('REDEMPTION', 'Resgate (Renda Fixa)')], help_text='Se preenchido, o plano totaliza transações de ativos deste tipo de operação (ex: DIVIDEND, JCP, BUY, SELL)', max_length=20, null=True, verbose_name='Tipo de operação de ativo'),
        ),
    ]
