# Generated by Django 4.2.27 on 2026-01-08 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_alter_chartaccount_asset_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChartAccount',
        ),
    ]
