# Generated by Django 4.2.23 on 2026-01-08 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_delete_chartaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(help_text='Código hierárquico (ex: 1.01, 1.01.1, 1.01.1.01)', max_length=50, unique=True, verbose_name='Código')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('calculation_type', models.CharField(choices=[('SUBTOTAL', 'Totaliza subníveis'), ('RULES', 'Calcula por regras')], default='RULES', help_text='SUBTOTAL: totaliza filhos ou itens que acumulam. RULES: calcula por regras configuradas.', max_length=20, verbose_name='Tipo de cálculo')),
                ('calculation_rules', models.JSONField(blank=True, default=list, help_text='\n        Lista de regras de cálculo. Exemplos:\n        \n        Por subcategoria:\n        [{"type": "subcategory", "subcategory_id": 5}]\n        \n        Por operação de ativo:\n        [{"type": "asset_operation", "operation_type": "DIVIDEND"}]\n        \n        Por operação + tipo de ativo:\n        [{"type": "asset_operation", "operation_type": "BUY", "asset_type": "STOCK"}]\n        \n        Múltiplas regras (soma todas):\n        [\n            {"type": "subcategory", "subcategory_id": 5},\n            {"type": "asset_operation", "operation_type": "DIVIDEND"}\n        ]\n        ')),
                ('order', models.IntegerField(default=0, help_text='Ordem de exibição', verbose_name='Ordem')),
                ('accumulates_in', models.ForeignKey(blank=True, help_text='Item onde este valor será acumulado (pode ser diferente do pai estrutural)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accumulated_items', to='finance.cashflowitem', verbose_name='Acumula em')),
            ],
            options={
                'verbose_name': 'Item do Fluxo de Caixa',
                'verbose_name_plural': 'Itens do Fluxo de Caixa',
                'ordering': ('order', 'code'),
                'indexes': [models.Index(fields=['code'], name='finance_cas_code_4e54e4_idx'), models.Index(fields=['calculation_type'], name='finance_cas_calcula_e6d196_idx'), models.Index(fields=['accumulates_in'], name='finance_cas_accumul_09793b_idx')],
            },
        ),
    ]
