# Generated by Django 4.2.23 on 2026-01-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_cash_flow_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status_reconciliado',
            field=models.BooleanField(default=False, help_text='Indica se esta transação foi reconciliada', verbose_name='Status reconciliado'),
        ),
    ]
