# Generated by Django 4.2.23 on 2026-01-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_transaction_status_reconciliado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='status_reconciliado',
        ),
        migrations.AlterField(
            model_name='assetposition',
            name='quantity',
            field=models.DecimalField(decimal_places=8, max_digits=15, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='assettransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Quantidade de ativos (0 para dividendos, juros, etc.)', max_digits=15, verbose_name='Quantidade'),
        ),
    ]
