# Generated by Django 4.2.23 on 2026-01-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_increase_quantity_decimal_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='recurrence_type',
            field=models.CharField(choices=[('NONE', 'Único (sem recorrência)'), ('DAILY', 'Diária'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensal'), ('YEARLY', 'Anual')], default='MONTHLY', max_length=10, verbose_name='Tipo de recorrência'),
        ),
    ]
