# Generated by Django 4.2.23 on 2026-01-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_add_none_recurrence_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='import_hash',
            field=models.CharField(blank=True, help_text='Hash MD5 gerado a partir dos dados originais da importação para prevenir duplicatas', max_length=32, null=True, unique=True, verbose_name='Hash de importação'),
        ),
    ]
