# Generated by Django 4.2.23 on 2026-01-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_add_import_hash_to_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(
                choices=[
                    ('CASH', 'Dinheiro'),
                    ('BANK', 'Banco'),
                    ('INVEST', 'Investimento'),
                    ('CREDCARD', 'Cartão de crédito'),
                    ('FIXED', 'Imobilizado'),
                ],
                default='BANK',
                max_length=10,
                verbose_name='Tipo'
            ),
        ),
    ]
