# Generated by Django 4.2.27 on 2026-01-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0030_add_asset_transaction_category_config'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assettransactioncategoryconfig',
            new_name='finance_ass_operati_12aec4_idx',
            old_name='finance_ass_operati_idx',
        ),
        migrations.AlterField(
            model_name='cashflowitem',
            name='calculation_rules',
            field=models.JSONField(blank=True, default=list, help_text='\n        Lista de regras de cálculo. Exemplos:\n        \n        Por subcategoria:\n        [{"type": "subcategory", "subcategory_id": 5}]\n        \n        Múltiplas regras (soma todas):\n        [\n            {"type": "subcategory", "subcategory_id": 5},\n            {"type": "subcategory", "subcategory_id": 10}\n        ]\n        \n        Nota: As transações de ativos agora geram Transactions normais que podem ser categorizadas por subcategoria.\n        '),
        ),
    ]
