# Generated by Django 4.2.27 on 2026-01-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0033_remove_unique_together_budget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ('budget_date', 'subcategory', 'notes'), 'verbose_name': 'Orçamento', 'verbose_name_plural': 'Orçamentos'},
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['subcategory', 'budget_date', 'notes'], name='finance_bud_subcate_c383b4_idx'),
        ),
    ]
