# Generated by Django 4.2.27 on 2026-01-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0035_add_import_hash_to_assettransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflowitem',
            name='calculation_rules',
            field=models.JSONField(blank=True, default=list, help_text='\n        Lista de regras de cálculo. Exemplos:\n        \n        Por subcategoria:\n        [{"type": "subcategory", "subcategory_id": 5}]\n        \n        Por transferência (crédito na conta de destino - valor recebido):\n        [{"type": "transfer", "destination_account_id": 5, "value_type": "credit"}]\n        \n        Por transferência (débito nas contas de origem - valor enviado):\n        [{"type": "transfer", "destination_account_id": 5, "value_type": "debit"}]\n        \n        Múltiplas regras (soma todas):\n        [\n            {"type": "subcategory", "subcategory_id": 5},\n            {"type": "subcategory", "subcategory_id": 10},\n            {"type": "transfer", "destination_account_id": 3, "value_type": "credit"}\n        ]\n        \n        Nota: As transações de ativos agora geram Transactions normais que podem ser categorizadas por subcategoria.\n        Nota: Regras antigas com "direction" são automaticamente migradas (direction="to" → value_type="credit", direction="from" → value_type="debit").\n        '),
        ),
    ]
