# Generated by Django 4.2.27 on 2026-02-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0038_add_assessoria_invoice_to_assettransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettransaction',
            name='operation_type',
            field=models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venda'), ('DIVIDEND', 'Dividendo'), ('JCP', 'Juros sobre Capital Próprio'), ('BONUS', 'Bonificação'), ('SPLIT', 'Desdobramento'), ('GROUP', 'Grupamento'), ('SUB', 'Subscrição'), ('CAPITAL_INCREASE', 'Aumento de Capital'), ('RIGHTS_EXERCISE', 'Exercício de Direitos'), ('AMORTIZATION', 'Amortização'), ('INTEREST', 'Juros (Renda Fixa)'), ('REDEMPTION', 'Resgate (Renda Fixa)'), ('TRANSFER_IN', 'Transferência Entrada'), ('PORTABILITY', 'Portabilidade')], max_length=20, verbose_name='Tipo de operação'),
        ),
        migrations.AlterField(
            model_name='assettransactioncategoryconfig',
            name='operation_type',
            field=models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venda'), ('DIVIDEND', 'Dividendo'), ('JCP', 'Juros sobre Capital Próprio'), ('BONUS', 'Bonificação'), ('SPLIT', 'Desdobramento'), ('GROUP', 'Grupamento'), ('SUB', 'Subscrição'), ('CAPITAL_INCREASE', 'Aumento de Capital'), ('RIGHTS_EXERCISE', 'Exercício de Direitos'), ('AMORTIZATION', 'Amortização'), ('INTEREST', 'Juros (Renda Fixa)'), ('REDEMPTION', 'Resgate (Renda Fixa)'), ('TRANSFER_IN', 'Transferência Entrada'), ('PORTABILITY', 'Portabilidade')], help_text='Tipo de operação de ativo (BUY, SELL, DIVIDEND, etc.)', max_length=20, verbose_name='Tipo de operação'),
        ),
        migrations.AlterField(
            model_name='cashflowitem',
            name='calculation_rules',
            field=models.JSONField(blank=True, default=list, help_text='\n        Lista de regras de cálculo. Exemplos:\n        \n        Por subcategoria:\n        [{"type": "subcategory", "subcategory_id": 5}]\n        \n        Por transferência (crédito na conta de destino - valor recebido):\n        [{"type": "transfer", "destination_account_id": 5, "value_type": "credit"}]\n        \n        Por transferência (débito nas contas de origem - valor enviado):\n        [{"type": "transfer", "destination_account_id": 5, "value_type": "debit"}]\n        \n        Por transação de ativo (compras de ações):\n        [{"type": "asset_transaction", "operation_type": "BUY", "asset_value_type": "net_value"}]\n        \n        Por transação de ativo (dividendos de FIIs):\n        [{"type": "asset_transaction", "operation_type": "DIVIDEND", "asset_type": "FII", "asset_value_type": "income_value"}]\n        \n        Por transação de ativo (compras de renda fixa):\n        [{"type": "asset_transaction", "operation_type": "BUY", "asset_type": "BOND", "asset_value_type": "net_value"}]\n        \n        Múltiplas regras (soma todas):\n        [\n            {"type": "subcategory", "subcategory_id": 5},\n            {"type": "subcategory", "subcategory_id": 10},\n            {"type": "transfer", "destination_account_id": 3, "value_type": "credit"},\n            {"type": "asset_transaction", "operation_type": "DIVIDEND", "asset_value_type": "income_value"}\n        ]\n        \n        Nota: As transações de ativos agora geram Transactions normais que podem ser categorizadas por subcategoria.\n        Nota: Regras antigas com "direction" são automaticamente migradas (direction="to" → value_type="credit", direction="from" → value_type="debit").\n        '),
        ),
    ]
