"""
Constants for the finance app.
Used for pagination, API limits, and transaction type literals.
"""

# Pagination
TRANSACTIONS_PER_PAGE = 50
ACCOUNTS_PER_PAGE = 25
SCHEDULERS_PER_PAGE = 50
ASSETS_PER_PAGE = 50
ASSET_TRANSACTIONS_PER_PAGE = 50
BUDGETS_PER_PAGE = 50
IMPORT_STAGING_TRANSACTIONS_PER_PAGE = 100
IMPORT_STAGING_ASSET_TRANSACTIONS_PER_PAGE = 100

# Chat
CHAT_HISTORY_MAX_MESSAGES = 20

# Transaction types (mirror Subcategory.TRANSACTION_TYPE_CHOICES for use in views/services)
TRANSACTION_TYPE_CR = 'CR'
TRANSACTION_TYPE_DB = 'DB'

# Import batch size
TRANSACTIONS_IMPORT_BATCH_SIZE = 500
TRANSACTIONS_IMPORT_PROGRESS_LOG_INTERVAL = 5000
